# Generated by Django 4.0.4 on 2022-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_pessoas_quizz_rename_discrição_post_descrição_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
