# Generated by Django 4.0.4 on 2022-05-24 15:06

from django.db import migrations, models
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_pessoas_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projetos',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=portfolio.models.resolution_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
