# Generated by Django 4.0.4 on 2022-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_projetos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
