# Generated by Django 4.0.4 on 2022-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_projetos_ano_alter_projetos_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(related_name='cadeiras', to='portfolio.pessoas'),
        ),
    ]
