# Generated by Django 4.0.4 on 2022-05-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_cadeira_ano_cadeira_semetres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadeira',
            old_name='semetres',
            new_name='semestre',
        ),
    ]
