# Generated by Django 4.0.4 on 2022-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_semetres_cadeira_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('acrónimo', models.CharField(max_length=5)),
                ('ano', models.IntegerField(default=0)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('link', models.CharField(max_length=200)),
                ('descrição', models.CharField(max_length=50000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-prioridade']},
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'ordering': ['-imagem']},
        ),
    ]
