# Generated by Django 4.0.4 on 2022-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_tecnologias_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologias',
            name='descrição',
            field=models.CharField(max_length=5000),
        ),
    ]
