# Generated by Django 4.0.4 on 2022-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_tecnologias_descrição'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descrição', models.CharField(max_length=50000)),
                ('link', models.CharField(max_length=2000)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='tecnologias',
            name='link',
        ),
    ]
