# Generated by Django 4.0.4 on 2022-05-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_noticia_remove_tecnologias_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='idNoticia',
            field=models.IntegerField(default=0),
        ),
    ]
