# Generated by Django 4.0.4 on 2022-05-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_noticia_idnoticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='idNoticia',
            new_name='numero',
        ),
    ]
