# Generated by Django 4.0.4 on 2022-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_rename_idnoticia_noticia_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('acrónimo', models.CharField(max_length=5)),
                ('ano', models.IntegerField(default=0)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('descrição', models.CharField(max_length=5000)),
            ],
        ),
    ]
