# Generated by Django 4.0.4 on 2022-06-08 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_tecnologias2'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='imagem2',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
