# Generated by Django 4.0.4 on 2022-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_projetos_imagem2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologias2',
            name='logotipo2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
