# Generated by Django 4.0.4 on 2022-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_tecnologias2_logotipo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
