# Generated by Django 4.0.4 on 2022-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_projetofinaldecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetofinaldecurso',
            name='resumo',
            field=models.CharField(max_length=200000),
        ),
    ]
